<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\KarmaLevel;
use Illuminate\Database\Seeder;

final class KarmaLevelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $levels = [
            [
                'name' => 'autogenerated_karma_levels.novato_name',
                'required_karma' => 0,
                'badge' => '🌱',
                'description' => 'autogenerated_karma_levels.novato_description',
                'benefits' => [
                    'autogenerated_karma_levels.novato_benefits_0',
                    'autogenerated_karma_levels.novato_benefits_1',
                    'autogenerated_karma_levels.novato_seals',
                ],
            ],
            [
                'name' => 'autogenerated_karma_levels.aprendiz_name',
                'required_karma' => 200,
                'badge' => '🔍',
                'description' => 'autogenerated_karma_levels.aprendiz_description',
                'benefits' => [
                    'autogenerated_karma_levels.aprendiz_benefits_0',
                    'autogenerated_karma_levels.aprendiz_benefits_1',
                    'autogenerated_karma_levels.aprendiz_seals',
                ],
            ],
            [
                'name' => 'autogenerated_karma_levels.colaborador_name',
                'required_karma' => 1000,
                'badge' => '🌟',
                'description' => 'autogenerated_karma_levels.colaborador_description',
                'benefits' => [
                    'autogenerated_karma_levels.colaborador_benefits_0',
                    'autogenerated_karma_levels.colaborador_benefits_1',
                    'autogenerated_karma_levels.colaborador_seals',
                ],
            ],
            [
                'name' => 'autogenerated_karma_levels.experto_name',
                'required_karma' => 4000,
                'badge' => '🏆',
                'description' => 'autogenerated_karma_levels.experto_description',
                'benefits' => [
                    'autogenerated_karma_levels.experto_benefits_0',
                    'autogenerated_karma_levels.experto_benefits_1',
                    'autogenerated_karma_levels.experto_seals',
                ],
            ],
            [
                'name' => 'autogenerated_karma_levels.mentor_name',
                'required_karma' => 16000,
                'badge' => '👑',
                'description' => 'autogenerated_karma_levels.mentor_description',
                'benefits' => [
                    'autogenerated_karma_levels.mentor_benefits_0',
                    'autogenerated_karma_levels.mentor_benefits_1',
                    'autogenerated_karma_levels.mentor_seals',
                ],
            ],
            [
                'name' => 'autogenerated_karma_levels.sabio_name',
                'required_karma' => 40000,
                'badge' => '🔮',
                'description' => 'autogenerated_karma_levels.sabio_description',
                'benefits' => [
                    'autogenerated_karma_levels.sabio_benefits_0',
                    'autogenerated_karma_levels.sabio_benefits_1',
                    'autogenerated_karma_levels.sabio_seals',
                ],
            ],
            [
                'name' => 'autogenerated_karma_levels.leyenda_name',
                'required_karma' => 100000,
                'badge' => '⭐',
                'description' => 'autogenerated_karma_levels.leyenda_description',
                'benefits' => [
                    'autogenerated_karma_levels.leyenda_benefits_0',
                    'autogenerated_karma_levels.leyenda_benefits_1',
                    'autogenerated_karma_levels.leyenda_seals',
                ],
            ],
        ];

        foreach ($levels as $index => $level) {
            KarmaLevel::updateOrCreate(
                ['id' => $index + 1], // Find by ID (1-7)
                $level, // Update/create with all data
            );
        }
    }
}
