<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\KarmaEvent;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

final class KarmaEventsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        // Schedule a karma tide event to start in 2 hours and last 5 hours
        KarmaEvent::create([
            'name' => 'autogenerated_karma_events.tide_title',
            'type' => 'tide',
            'start_at' => $now->copy()->addHours(2),
            'end_at' => $now->copy()->addHours(7),
            'multiplier' => 2.0,
            'description' => 'autogenerated_karma_events.tide_description',
            'is_active' => true,
        ]);

        // Schedule a boost event for the weekend
        $nextSaturday = $now->copy()->nextWeekendDay();
        KarmaEvent::create([
            'name' => 'autogenerated_karma_events.boost_title',
            'type' => 'boost',
            'start_at' => $nextSaturday->copy()->setTime(12, 0),
            'end_at' => $nextSaturday->copy()->setTime(23, 59),
            'multiplier' => 1.5,
            'description' => 'autogenerated_karma_events.boost_description',
            'is_active' => true,
        ]);

        // Special event for new users (starts immediately)
        KarmaEvent::create([
            'name' => 'autogenerated_karma_events.welcome_title',
            'type' => 'welcome',
            'start_at' => $now,
            'end_at' => $now->copy()->addDays(7),
            'multiplier' => 1.25,
            'description' => 'autogenerated_karma_events.welcome_description',
            'is_active' => true,
        ]);
    }
}
