<?php

declare(strict_types=1);

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

/**
 * Controller for Bluesky OAuth API endpoints (stateless).
 * Handles status check and exchange code redemption.
 */
final class BlueskyAuthController extends Controller
{
    /**
     * Check if Bluesky login is enabled and return status.
     */
    public function status(): JsonResponse
    {
        $enabled = config('bluesky_login.enabled', false) === true
            && ! empty(config('bluesky_login.private_key'));

        return response()->json([
            'enabled' => $enabled,
        ]);
    }

    /**
     * Exchange a one-time code for a Sanctum token.
     * The code was generated by BlueskyWebAuthController after successful OAuth.
     */
    public function exchange(Request $request): JsonResponse
    {
        $request->validate([
            'exchange_code' => 'required|string|size:64',
        ]);

        /** @var string $code */
        $code = $request->input('exchange_code');

        // Retrieve and consume the exchange data from cache
        /** @var array{user_id: int}|null $exchangeData */
        $exchangeData = Cache::pull("bluesky_exchange:{$code}");

        if ($exchangeData === null) {
            return response()->json([
                'message' => 'Invalid or expired exchange code',
            ], 400);
        }

        // Find the user
        $user = \App\Models\User::find($exchangeData['user_id']);

        if ($user === null) {
            return response()->json([
                'message' => 'User not found',
            ], 400);
        }

        // Check if user is banned
        if ($user->isBanned()) {
            return response()->json([
                'message' => 'Your account has been banned',
            ], 403);
        }

        // Check if user is approved (for manual approval mode)
        if (config('bluesky_login.auto_approve') !== true && ! $user->isApproved()) {
            return response()->json([
                'message' => 'Your account is pending approval',
                'status' => 'pending',
            ], 403);
        }

        // Create Sanctum token
        $token = $user->createToken('bluesky-auth')->plainTextToken;

        return response()->json([
            'token' => $token,
            'user' => [
                'id' => $user->id,
                'username' => $user->username,
                'display_name' => $user->display_name,
                'avatar' => $user->avatar,
                'federated_handle' => $user->federated_handle,
                'is_federated' => true,
                'email_verified_at' => $user->email_verified_at,
            ],
        ]);
    }
}
