/**
 * AUTO-GENERATED FILE - DO NOT MODIFY MANUALLY
 * This file was automatically generated by the "php artisan languages:generate" command
 * Any changes should be made in the languages configuration (config/languages.php)
 * and then regenerate this file.
 *
 * Generated on: 2025-04-30 08:57:12
 */

export const languages = [
    {
        "code": "en",
        "name": "English",
        "native": "English",
        "flag": "gb",
        "active": true
    },
    {
        "code": "es",
        "name": "Spanish",
        "native": "Espa\u00f1ol",
        "flag": "es",
        "active": true
    }
];

export const currentLocale = "en";
