<?php

declare(strict_types=1);

namespace App\Notifications;

use App\Models\Achievement;
use App\Notifications\Concerns\HasWebPush;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

final class AchievementUnlocked extends Notification implements ShouldQueue
{
    use HasWebPush;

    use Queueable;

    protected $achievement;

    /**
     * Create a new notification instance.
     */
    public function __construct(Achievement $achievement)
    {
        $this->achievement = $achievement;
    }

    /**
     * Get the notification's delivery channels.
     *
     * @return array<int, string>
     */
    public function via(object $notifiable): array
    {
        return $this->getChannelsWithWebPush($notifiable, ['database', 'broadcast']);
    }

    protected function getPushCategory(): string
    {
        return 'achievements';
    }

    protected function getPushTitle(): string
    {
        return __('notifications.push.achievement_title');
    }

    protected function getPushBody(): string
    {
        return __('notifications.push.achievement_body', [
            'achievement' => __($this->achievement->name),
        ]);
    }

    protected function getPushUrl(): string
    {
        return '/profile/achievements';
    }

    /**
     * Get the mail representation of the notification.
     */
    public function toMail(object $notifiable): MailMessage
    {
        $locale = $notifiable->locale ?? 'es';
        $achievementsUrl = config('app.client_url') ? config('app.client_url') . "/{$locale}/profile/achievements" : url('/profile/achievements');

        return (new MailMessage())
            ->subject(__('notifications.achievement_unlocked_title', [], $locale))
            ->greeting(__('notifications.greeting', [], $locale) . " {$notifiable->username}!")
            ->line(__('notifications.achievement_unlocked_body', ['achievement' => $this->achievement->name], $locale))
            ->line($this->achievement->description)
            ->line(__('notifications.karma_earned', ['karma' => $this->achievement->karma_bonus], $locale))
            ->action(__('notifications.view_achievements', [], $locale), $achievementsUrl)
            ->line(__('notifications.keep_participating', [], $locale));
    }

    /**
     * Get the database representation of the notification.
     *
     * @return array<string, mixed>
     */
    public function toDatabase(object $notifiable): array
    {
        $locale = $notifiable->locale ?? 'es';
        $achievementName = __($this->achievement->name, [], $locale);
        $karmaBonus = $this->achievement->karma_bonus;

        return [
            'title' => '🏆 ' . __('notifications.achievement_unlocked_title', [], $locale),
            'body' => __('notifications.achievement_unlocked_body', ['achievement' => $achievementName], $locale) . ' ' . __('notifications.karma_earned', ['karma' => $karmaBonus], $locale),
            'icon' => $this->achievement->icon,
            'action_url' => null,
        ];
    }

    /**
     * Get the array representation of the notification.
     *
     * @return array<string, mixed>
     */
    public function toArray(object $notifiable): array
    {
        // Set locale for this notification
        $previousLocale = app()->getLocale();
        app()->setLocale($notifiable->locale ?? 'es');

        // Translate achievement name if it's a translation key
        $displayName = $this->achievement->name;
        if (str_starts_with($displayName, 'achievements.') || str_starts_with($displayName, 'autogenerated_achievements.')) {
            $translated = __($displayName);
            $displayName = $translated === $displayName ? $displayName : $translated;
        }

        // Translate description if it's a translation key
        $displayDescription = $this->achievement->description;
        if (str_starts_with($displayDescription, 'achievements.') || str_starts_with($displayDescription, 'autogenerated_achievements.')) {
            $translated = __($displayDescription);
            $displayDescription = $translated === $displayDescription ? $displayDescription : $translated;
        }

        // Get motivational message based on achievement type
        $motivationalKey = $this->getMotivationalKey($this->achievement->slug);

        // Build message body
        $body = __('notifications.achievement_unlocked_congrats') . "\n\n";
        $body .= __('notifications.achievement_unlocked_body', ['achievement' => $displayName]);

        if ($displayDescription) {
            $body .= ' ' . $displayDescription;
        }

        if ($this->achievement->karma_bonus > 0) {
            $body .= "\n\n" . __('notifications.karma_earned', ['karma' => $this->achievement->karma_bonus]);
        }

        // Add motivational message
        if ($motivationalKey) {
            $body .= "\n\n" . __($motivationalKey);
        }

        $data = [
            'title' => __('notifications.achievement_unlocked_title'),
            'body' => trim($body),
            'achievement_id' => $this->achievement->id,
            'achievement_name' => $displayName, // Translated name only
            'karma_bonus' => $this->achievement->karma_bonus,
            'action_url' => null, // No specific action needed - user is already on notifications page
        ];

        // Restore previous locale
        app()->setLocale($previousLocale);

        return $data;
    }

    /**
     * Get the broadcastable representation of the notification.
     *
     * @return array
     */
    public function toBroadcast($notifiable)
    {
        $locale = $notifiable->locale ?? 'es';

        return [
            'achievement_id' => $this->achievement->id,
            'title' => __('notifications.achievement_unlocked_title', [], $locale),
            'body' => __('notifications.achievement_unlocked_body', ['achievement' => $this->achievement->name], $locale),
            'icon' => $this->achievement->icon,
            'karma_bonus' => $this->achievement->karma_bonus,
            'timestamp' => now()->toIso8601String(),
        ];
    }

    /**
     * Get motivational message key based on achievement type.
     */
    private function getMotivationalKey(string $slug): ?string
    {
        // Welcome and special achievements
        if (in_array($slug, ['welcome', 'early_adopter', 'featured_collaborator'])) {
            return 'notifications.achievement_motivation_welcome';
        }

        // First actions
        if (in_array($slug, ['first_post', 'first_comment', 'first_vote'])) {
            return 'notifications.achievement_motivation_first';
        }

        // Posts achievements
        if (str_starts_with($slug, 'posts_')) {
            return 'notifications.achievement_motivation_posts';
        }

        // Comments achievements
        if (str_starts_with($slug, 'comments_') || $slug === 'conversationalist') {
            return 'notifications.achievement_motivation_comments';
        }

        // Votes achievements
        if (str_starts_with($slug, 'votes_') || $slug === 'active_voter') {
            return 'notifications.achievement_motivation_votes';
        }

        // Streak achievements
        if (str_starts_with($slug, 'streak_')) {
            return 'notifications.achievement_motivation_streak';
        }

        // Karma milestones
        if (str_starts_with($slug, 'karma_') || $slug === 'karma_master') {
            return 'notifications.achievement_motivation_karma';
        }

        // Community achievements
        if (in_array($slug, ['content_creator', 'community_pillar'])) {
            return 'notifications.achievement_motivation_community';
        }

        return null;
    }
}
