<?php

declare(strict_types=1);

namespace App\Notifications;

use App\Models\KarmaLevel;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

final class KarmaLevelUp extends Notification implements ShouldQueue
{
    use Queueable;

    protected $level;

    /**
     * Create a new notification instance.
     */
    public function __construct(KarmaLevel $level)
    {
        $this->level = $level;
    }

    /**
     * Get the notification's delivery channels.
     *
     * @return array<int, string>
     */
    public function via(object $notifiable): array
    {
        // In-app notifications only (bell icon + real-time)
        return ['database', 'broadcast'];
    }

    /**
     * Get the mail representation of the notification.
     */
    public function toMail(object $notifiable): MailMessage
    {
        $locale = $notifiable->locale ?? 'es';
        $profileUrl = config('app.client_url') ? config('app.client_url') . "/{$locale}/profile" : url('/profile');

        return (new MailMessage())
            ->subject(__('notifications.karma_level_up_title', [], $locale))
            ->greeting(__('notifications.greeting', [], $locale) . " {$notifiable->username}!")
            ->line(__('notifications.karma_level_up_body', ['level' => $this->level->name], $locale))
            ->line($this->level->description)
            ->lineIf(! empty($this->level->benefits), __('notifications.benefits', [], $locale) . ':')
            ->when(! empty($this->level->benefits), function ($message) {
                $benefitsList = '';
                foreach ($this->level->benefits as $benefit) {
                    $benefitsList .= "- {$benefit}\n";
                }

                return $message->line($benefitsList);
            })
            ->action(__('notifications.view_profile', [], $locale), $profileUrl)
            ->line(__('notifications.keep_participating', [], $locale));
    }

    /**
     * Get the database representation of the notification.
     *
     * @return array<string, mixed>
     */
    public function toDatabase(object $notifiable): array
    {
        $locale = $notifiable->locale ?? 'es';
        $levelName = __($this->level->name, [], $locale);
        $badge = $this->level->badge;

        $bodyHtml = __('notifications.karma_level_up_body', ['level' => "<strong>\"{$levelName}\"</strong>"], $locale)
                  . '<br><br>' . __('notifications.keep_participating', [], $locale);

        return [
            'title' => "{$badge} " . __('notifications.karma_level_up_title', [], $locale),
            'body' => $bodyHtml,
            'icon' => $badge,
            'action_url' => null,
        ];
    }

    /**
     * Get the array representation of the notification.
     *
     * @return array<string, mixed>
     */
    public function toArray(object $notifiable): array
    {
        // Set locale for this notification
        $previousLocale = app()->getLocale();
        app()->setLocale($notifiable->locale ?? 'es');

        // Translate level name
        $displayName = $this->level->name;
        if (str_starts_with($displayName, 'autogenerated_karma_levels.')) {
            $translated = __($displayName);
            $displayName = $translated === $displayName
                ? "{$this->level->badge} " . __('karma_events.level_with_points', ['points' => $this->level->required_karma])
                : $translated;
        }

        // Translate benefits
        $translatedBenefits = [];
        if (! empty($this->level->benefits)) {
            foreach ($this->level->benefits as $benefit) {
                if (str_starts_with($benefit, 'autogenerated_karma_levels.')) {
                    $translated = __($benefit);
                    $translatedBenefits[] = $translated === $benefit ? $benefit : $translated;
                } else {
                    $translatedBenefits[] = $benefit;
                }
            }
        }

        // Translate level description
        $displayDescription = $this->level->description;
        if (str_starts_with($displayDescription, 'autogenerated_karma_levels.')) {
            $translated = __($displayDescription);
            $displayDescription = $translated === $displayDescription ? '' : $translated;
        }

        // Build message body with name, description, and karma
        $body = __('notifications.karma_level_up_body', ['level' => $displayName]);

        // Add description if available
        if (! empty($displayDescription)) {
            $body .= ' ' . $displayDescription;
        }

        // Add total karma
        $body .= "\n\n" . __('notifications.total_karma', ['karma' => number_format($notifiable->karma_points, 0, ',', '.')]);

        // Add benefits if any (currently none)
        if (! empty($translatedBenefits)) {
            $body .= "\n\n" . __('notifications.benefits') . ":\n";
            foreach ($translatedBenefits as $benefit) {
                $body .= "• {$benefit}\n";
            }
        }

        $data = [
            'title' => __('notifications.karma_level_up_title'),
            'body' => trim($body),
            'level_id' => $this->level->id,
            'badge' => $this->level->badge,
            'level_name' => $displayName, // Translated name only
            'action_url' => null, // No specific action needed - user is already on notifications page
        ];

        // Restore previous locale
        app()->setLocale($previousLocale);

        return $data;
    }

    /**
     * Get the broadcastable representation of the notification.
     *
     * @return array
     */
    public function toBroadcast($notifiable)
    {
        $locale = $notifiable->locale ?? 'es';

        return [
            'level_id' => $this->level->id,
            'title' => __('notifications.karma_level_up_title', [], $locale),
            'body' => __('notifications.karma_level_up_body', ['level' => $this->level->name], $locale),
            'badge' => $this->level->badge,
            'timestamp' => now()->toIso8601String(),
        ];
    }
}
