<?php

declare(strict_types=1);

namespace Tests\Feature\Api;

use App\Models\KarmaHistory;
use App\Models\KarmaLevel;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

final class KarmaControllerTest extends TestCase
{
    use RefreshDatabase;

    protected $user;

    protected $token;

    protected $levels = [];

    protected function setUp(): void
    {
        parent::setUp();

        // Use the real karma levels from the seed migration
        // Levels: Novato (0), Aprendiz (200), Colaborador (1000), Experto (4000), Mentor (16000), Sabio (40000), Leyenda (100000)
        $this->levels = KarmaLevel::orderBy('required_karma')->get()->all();

        $this->user = User::factory()->create([
            'karma_points' => 500,
            'highest_level_id' => $this->levels[1]->id, // Aprendiz (200)
        ]);

        $this->token = $this->user->createToken('auth_token')->plainTextToken;
    }

    #[Test]
    public function it_can_show_user_karma_details(): void
    {
        KarmaHistory::create([
            'user_id' => $this->user->id,
            'amount' => 10,
            'source' => 'post_created',
            'description' => 'Created a post',
        ]);

        KarmaHistory::create([
            'user_id' => $this->user->id,
            'amount' => 5,
            'source' => 'comment_upvoted',
            'description' => 'Comment was upvoted',
        ]);

        $response = $this->withHeaders([
            'Authorization' => 'Bearer ' . $this->token,
        ])->getJson("/api/v1/users/{$this->user->id}/karma");

        $response->assertStatus(200);

        $responseData = $response->json('data');
        $this->assertEquals($this->user->id, $responseData['user_id']);
        $this->assertEquals(500, $responseData['karma_points']);
        $this->assertEquals($this->levels[1]->id, $responseData['level']['id']); // Aprendiz
        $this->assertEquals('autogenerated_karma_levels.aprendiz_name', $responseData['level']['name']);
        $this->assertEquals('🔍', $responseData['level']['badge']);

        $this->assertEquals($this->levels[2]->id, $responseData['next_level']['id']); // Colaborador
        $this->assertEquals('autogenerated_karma_levels.colaborador_name', $responseData['next_level']['name']);
        $this->assertEquals(1000, $responseData['next_level']['required_karma']);
        $this->assertEquals(500, $responseData['next_level']['points_needed']); // 1000 - 500 = 500

        $this->assertCount(2, $responseData['recent_history']);
    }

    #[Test]
    public function it_can_list_all_karma_levels(): void
    {
        $response = $this->withHeaders([
            'Authorization' => 'Bearer ' . $this->token,
        ])->getJson('/api/v1/karma/levels');

        $response->assertStatus(200);

        $responseData = $response->json('data');
        $this->assertCount(7, $responseData);
        $this->assertEquals('autogenerated_karma_levels.novato_name', $responseData[0]['name']);
        $this->assertEquals('autogenerated_karma_levels.aprendiz_name', $responseData[1]['name']);
        $this->assertEquals('autogenerated_karma_levels.colaborador_name', $responseData[2]['name']);
        $this->assertEquals('autogenerated_karma_levels.experto_name', $responseData[3]['name']);
        $this->assertEquals('autogenerated_karma_levels.mentor_name', $responseData[4]['name']);
        $this->assertEquals('autogenerated_karma_levels.sabio_name', $responseData[5]['name']);
        $this->assertEquals('autogenerated_karma_levels.leyenda_name', $responseData[6]['name']);
    }

    #[Test]
    public function it_can_show_karma_leaderboard(): void
    {
        $user1 = User::factory()->create(['karma_points' => 200, 'highest_level_id' => $this->levels[2]->id]);
        $user2 = User::factory()->create(['karma_points' => 75, 'highest_level_id' => $this->levels[1]->id]);
        $user3 = User::factory()->create(['karma_points' => 300, 'highest_level_id' => $this->levels[2]->id]);

        $response = $this->withHeaders([
            'Authorization' => 'Bearer ' . $this->token,
        ])->getJson('/api/v1/karma/leaderboard');

        $response->assertStatus(200)
            ->assertJsonStructure([
                'data' => [
                    'data' => [
                        '*' => [
                            'karma_points',
                        ],
                    ],
                    'current_page',
                    'per_page',
                    'total',
                ],
            ]);
    }

    #[Test]
    public function it_can_paginate_leaderboard(): void
    {
        for ($i = 1; $i <= 15; $i++) {
            User::factory()->create([
                'karma_points' => 100 + $i * 10,
                'highest_level_id' => $this->levels[1]->id,
            ]);
        }

        $response = $this->withHeaders([
            'Authorization' => 'Bearer ' . $this->token,
        ])->getJson('/api/v1/karma/leaderboard?limit=5&page=2');

        $response->assertStatus(200)
            ->assertJsonStructure([
                'data' => [
                    'data' => [
                        '*' => [
                            'karma_points',
                        ],
                    ],
                    'current_page',
                    'per_page',
                    'total',
                ],
            ]);

        // Verify we are on page 2
        $responseData = $response->json('data');
        $this->assertEquals(2, $responseData['current_page']);
        $this->assertEquals(5, $responseData['per_page']);
    }

    #[Test]
    public function it_returns_empty_next_level_when_at_max_level(): void
    {
        $this->user->karma_points = 100000;
        $this->user->highest_level_id = $this->levels[6]->id; // Leyenda
        $this->user->save();

        $response = $this->withHeaders([
            'Authorization' => 'Bearer ' . $this->token,
        ])->getJson("/api/v1/users/{$this->user->id}/karma");

        $response->assertStatus(200);

        $responseData = $response->json('data');
        $this->assertEquals($this->user->id, $responseData['user_id']);
        $this->assertEquals(100000, $responseData['karma_points']);
        $this->assertEquals($this->levels[6]->id, $responseData['level']['id']);
        $this->assertEquals('autogenerated_karma_levels.leyenda_name', $responseData['level']['name']);
        $this->assertNull($responseData['next_level']);
    }

    #[Test]
    public function it_handles_users_with_no_karma_history(): void
    {
        $newUser = User::factory()->create([
            'karma_points' => 0,
            'highest_level_id' => $this->levels[0]->id,
        ]);

        $response = $this->withHeaders([
            'Authorization' => 'Bearer ' . $this->token,
        ])->getJson("/api/v1/users/{$newUser->id}/karma");

        $response->assertStatus(200);

        $responseData = $response->json('data');
        $this->assertEquals($newUser->id, $responseData['user_id']);
        $this->assertEquals(0, $responseData['karma_points']);
        $this->assertEquals($this->levels[0]->id, $responseData['level']['id']);
        $this->assertEquals('autogenerated_karma_levels.novato_name', $responseData['level']['name']);
        $this->assertCount(0, $responseData['recent_history']);
    }
}
