<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class() extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $levels = [
            [
                'id' => 1,
                'name' => 'autogenerated_karma_levels.novato_name',
                'required_karma' => 0,
                'badge' => '🌱',
                'description' => 'autogenerated_karma_levels.novato_description',
                'benefits' => json_encode([
                    'autogenerated_karma_levels.novato_benefits_0',
                    'autogenerated_karma_levels.novato_benefits_1',
                    'autogenerated_karma_levels.novato_seals',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'autogenerated_karma_levels.aprendiz_name',
                'required_karma' => 200,
                'badge' => '🔍',
                'description' => 'autogenerated_karma_levels.aprendiz_description',
                'benefits' => json_encode([
                    'autogenerated_karma_levels.aprendiz_benefits_0',
                    'autogenerated_karma_levels.aprendiz_benefits_1',
                    'autogenerated_karma_levels.aprendiz_seals',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'autogenerated_karma_levels.colaborador_name',
                'required_karma' => 1000,
                'badge' => '🌟',
                'description' => 'autogenerated_karma_levels.colaborador_description',
                'benefits' => json_encode([
                    'autogenerated_karma_levels.colaborador_benefits_0',
                    'autogenerated_karma_levels.colaborador_benefits_1',
                    'autogenerated_karma_levels.colaborador_seals',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'autogenerated_karma_levels.experto_name',
                'required_karma' => 4000,
                'badge' => '🏆',
                'description' => 'autogenerated_karma_levels.experto_description',
                'benefits' => json_encode([
                    'autogenerated_karma_levels.experto_benefits_0',
                    'autogenerated_karma_levels.experto_benefits_1',
                    'autogenerated_karma_levels.experto_seals',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'autogenerated_karma_levels.mentor_name',
                'required_karma' => 16000,
                'badge' => '👑',
                'description' => 'autogenerated_karma_levels.mentor_description',
                'benefits' => json_encode([
                    'autogenerated_karma_levels.mentor_benefits_0',
                    'autogenerated_karma_levels.mentor_benefits_1',
                    'autogenerated_karma_levels.mentor_seals',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'autogenerated_karma_levels.sabio_name',
                'required_karma' => 40000,
                'badge' => '🔮',
                'description' => 'autogenerated_karma_levels.sabio_description',
                'benefits' => json_encode([
                    'autogenerated_karma_levels.sabio_benefits_0',
                    'autogenerated_karma_levels.sabio_benefits_1',
                    'autogenerated_karma_levels.sabio_seals',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'autogenerated_karma_levels.leyenda_name',
                'required_karma' => 100000,
                'badge' => '⭐',
                'description' => 'autogenerated_karma_levels.leyenda_description',
                'benefits' => json_encode([
                    'autogenerated_karma_levels.leyenda_benefits_0',
                    'autogenerated_karma_levels.leyenda_benefits_1',
                    'autogenerated_karma_levels.leyenda_seals',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($levels as $level) {
            DB::table('karma_levels')->updateOrInsert(
                ['id' => $level['id']],
                $level,
            );
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // We don't delete levels on rollback to avoid data loss
        // If you really need to delete them, uncomment the following line:
        // DB::table('karma_levels')->whereIn('id', [1, 2, 3, 4, 5, 6, 7])->delete();
    }
};
