<?php

declare(strict_types=1);

use App\Models\KarmaLevel;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class() extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $levels = [
            [
                'name' => 'autogenerated_karma_levels.novato_name',
                'required_karma' => 0,
                'badge' => '🌱',
                'description' => 'autogenerated_karma_levels.novato_description',
                'benefits' => [
                    'autogenerated_karma_levels.novato_benefits_0',
                    'autogenerated_karma_levels.novato_benefits_1',
                ],
            ],
            [
                'name' => 'autogenerated_karma_levels.aprendiz_name',
                'required_karma' => 200,
                'badge' => '🔍',
                'description' => 'autogenerated_karma_levels.aprendiz_description',
                'benefits' => [
                    'autogenerated_karma_levels.aprendiz_benefits_0',
                    'autogenerated_karma_levels.aprendiz_benefits_1',
                ],
            ],
            [
                'name' => 'autogenerated_karma_levels.colaborador_name',
                'required_karma' => 1000,
                'badge' => '🌟',
                'description' => 'autogenerated_karma_levels.colaborador_description',
                'benefits' => [
                    'autogenerated_karma_levels.colaborador_benefits_0',
                    'autogenerated_karma_levels.colaborador_benefits_1',
                ],
            ],
            [
                'name' => 'autogenerated_karma_levels.experto_name',
                'required_karma' => 4000,
                'badge' => '🏆',
                'description' => 'autogenerated_karma_levels.experto_description',
                'benefits' => [
                    'autogenerated_karma_levels.experto_benefits_0',
                    'autogenerated_karma_levels.experto_benefits_1',
                ],
            ],
            [
                'name' => 'autogenerated_karma_levels.mentor_name',
                'required_karma' => 16000,
                'badge' => '👑',
                'description' => 'autogenerated_karma_levels.mentor_description',
                'benefits' => [
                    'autogenerated_karma_levels.mentor_benefits_0',
                    'autogenerated_karma_levels.mentor_benefits_1',
                ],
            ],
            [
                'name' => 'autogenerated_karma_levels.sabio_name',
                'required_karma' => 40000,
                'badge' => '🔮',
                'description' => 'autogenerated_karma_levels.sabio_description',
                'benefits' => [
                    'autogenerated_karma_levels.sabio_benefits_0',
                    'autogenerated_karma_levels.sabio_benefits_1',
                ],
            ],
            [
                'name' => 'autogenerated_karma_levels.leyenda_name',
                'required_karma' => 100000,
                'badge' => '⭐',
                'description' => 'autogenerated_karma_levels.leyenda_description',
                'benefits' => [
                    'autogenerated_karma_levels.leyenda_benefits_0',
                    'autogenerated_karma_levels.leyenda_benefits_1',
                ],
            ],
        ];

        // Cleanup migration already deleted all old levels
        // Therefore, we create new levels directly with specific IDs
        foreach ($levels as $index => $level) {
            $level['id'] = $index + 1; // Assign IDs 1-7
            KarmaLevel::create($level);
        }

        // After creating levels, recalculate user levels
        // Compare with old levels saved in JSON file
        // Only send notifications if user ACTUALLY leveled up

        $oldLevelsFile = storage_path('app/old_karma_levels.json');
        $oldLevels = collect();

        if (file_exists($oldLevelsFile)) {
            $oldLevels = collect(json_decode(file_get_contents($oldLevelsFile), true));
        }

        // Use DB::table() to avoid SoftDeletes trait issues during migrations
        $users = DB::table('users')->get()->map(fn ($user) => (object) [
            'id' => $user->id,
            'karma_points' => $user->karma_points ?? 0,
            'highest_level_id' => $user->highest_level_id,
        ]);

        foreach ($users as $user) {
            // Calcular el nuevo nivel basado en karma actual
            $newLevel = KarmaLevel::where('required_karma', '<=', $user->karma_points ?? 0)
                ->orderBy('required_karma', 'desc')
                ->first();

            if (! $newLevel) {
                continue;
            }

            // Get the karma from the old level
            $oldLevelData = $oldLevels->get($user->id);
            $oldLevelKarma = $oldLevelData ? ($oldLevelData['old_level_karma'] ?? 0) : 0;

            // Set the new level using DB::table() to avoid SoftDeletes
            DB::table('users')->where('id', $user->id)->update([
                'highest_level_id' => $newLevel->id,
            ]);

            // Skip notifications during migration to avoid issues
            // Notifications and events will be sent naturally when users earn karma after migration
        }

        // Limpiar archivo temporal
        if (file_exists($oldLevelsFile)) {
            unlink($oldLevelsFile);
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // Optional: delete all seeded karma levels
        // KarmaLevel::whereIn('id', [1, 2, 3, 4, 5, 6, 7])->delete();
    }
};
