<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * @property int $id
 * @property string $name
 * @property string|null $type
 * @property string $description
 * @property float $multiplier
 * @property bool $is_active
 * @property \Illuminate\Support\Carbon|null $start_at
 * @property \Illuminate\Support\Carbon|null $end_at
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read string $translated_description
 * @property-read string $translated_name
 *
 * @method static \Illuminate\Database\Eloquent\Builder<static>|KarmaEvent active()
 * @method static \Database\Factories\KarmaEventFactory factory($count = null, $state = [])
 * @method static \Illuminate\Database\Eloquent\Builder<static>|KarmaEvent newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|KarmaEvent newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|KarmaEvent query()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|KarmaEvent upcoming()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|KarmaEvent whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|KarmaEvent whereDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|KarmaEvent whereEndAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|KarmaEvent whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|KarmaEvent whereIsActive($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|KarmaEvent whereMultiplier($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|KarmaEvent whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|KarmaEvent whereStartAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|KarmaEvent whereType($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|KarmaEvent whereUpdatedAt($value)
 *
 * @mixin \Eloquent
 */
final class KarmaEvent extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'name',
        'type',
        'start_at',
        'end_at',
        'multiplier',
        'description',
        'is_active',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'start_at' => 'datetime',
        'end_at' => 'datetime',
        'multiplier' => 'float',
        'is_active' => 'boolean',
    ];

    /**
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeActive($query)
    {
        $now = now();

        return $query->where('is_active', true)
            ->where('start_at', '<=', $now)
            ->where('end_at', '>=', $now);
    }

    /**
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeUpcoming($query)
    {
        $now = now();

        return $query->where('is_active', true)
            ->where('start_at', '>', $now);
    }

    public function isActive(): bool
    {
        $now = now();

        return $this->is_active && $now->between($this->start_at, $this->end_at);
    }

    /**
     * Get currently active events.
     *
     * @return \Illuminate\Database\Eloquent\Collection<int, self>
     */
    public static function getActiveEvents(): \Illuminate\Database\Eloquent\Collection
    {
        $now = now();

        return self::where('is_active', true)
            ->where('start_at', '<=', $now)
            ->where('end_at', '>=', $now)
            ->get();
    }

    /**
     * Get the translated name attribute.
     */
    public function getTranslatedNameAttribute(): string
    {
        $translation = __($this->name);

        // If translation equals the key, it means translation is missing
        // Return the key without the namespace as fallback
        if ($translation === $this->name) {
            return str_replace(['autogenerated_karma_events.', 'karma_events.'], '', $this->name);
        }

        return $translation;
    }

    /**
     * Get the translated description attribute.
     */
    public function getTranslatedDescriptionAttribute(): string
    {
        $translation = __($this->description);

        // If translation equals the key, it means translation is missing
        // Return the key without the namespace as fallback
        if ($translation === $this->description) {
            return str_replace(['autogenerated_karma_events.', 'karma_events.'], '', $this->description);
        }

        return $translation;
    }

    /**
     * Check if this event was created through admin panel.
     */
    public function isAdminGenerated(): bool
    {
        return str_starts_with($this->name, 'autogenerated_');
    }

    /**
     * Get the module name for this event.
     */
    public function getModuleName(): string
    {
        if ($this->isAdminGenerated()) {
            return 'karma_events';
        }

        return 'core';
    }
}
